const countryList = {
    "USD": "US",
    "EUR": "EU",
    "GBP": "GB",
    "INR": "IN",
    "AUD": "AU",
    "CAD": "CA",
    "JPY": "JP",
    "CNY": "CN",
    "NZD": "NZ",
    "CHF": "CH",
    "ZAR": "ZA",
    "RUB": "RU",
    "SGD": "SG",
    "HKD": "HK",
    "MXN": "MX",
    "BRL": "BR",
    "KRW": "KR",
    "IDR": "ID",
    "TRY": "TR",
    "SAR": "SA",
    "SEK": "SE",
    "NOK": "NO",
    "DKK": "DK",
    "PLN": "PL",
    "THB": "TH",
    "AED": "AE"
};
